# Generated by Django 4.2.2 on 2024-01-21 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_constraints_alter_team_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 19, 24, 38, 256907)),
        ),
    ]
